# Generated by Django 5.0 on 2023-12-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketballLeague', '0003_alter_team_options_alter_playerprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('League Stage', 'League Stage'), ('Quarter-Final', 'Quarter-Final'), ('Semi-Final', 'Semi-Final'), ('Final', 'Final')], default='League Stage', max_length=50),
        ),
    ]
