# Generated by Django 5.0 on 2023-12-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketballLeague', '0006_rename_userstats_userlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='user',
            new_name='player',
        ),
    ]
